site_name: Lambda
site_url: https://lambda.pablob.eu/
theme:
  name: material
  logo: img/lambda.svg
  favicon: img/favicon.png
  language: es
  custom_dir: overrides
  font:
    text: Ubuntu
    code: Ubuntu mono
  palette:
    - scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
    - scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tooltips
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
  - css/styles.css
extra:
  link_copyright: https://github.com/pbl0/
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pbl0/lambda-rr
    - icon: fontawesome/solid/link
      link: https://pablob.eu
copyright: Copyright &copy; 2021-2022 Pablo
plugins:
  - search
  - glightbox
