site_name: Lambda
theme:
  name: material
  language: es
  palette:
    scheme: slate
    primary: deep orange
  features:
    - navigation.indexes
  logo: img/lambda.svg  
  favicon: img/favicon.png  
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
extra_css:
  - css/styles.css
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/pbl0
    - icon: fontawesome/solid/link
      link: https://pablob.eu
copyright: Copyright &copy; 2021 Pablo B
